[tool.poetry]
name = "vodka-az"
description = "Vodka A-Z"
version = "1.0.0"
authors = ["OpenAlcoholics <team@openalcoholics.group>"]
license = "MIT"
packages = [
    { include = "az", from = "src" }
]

[[tool.poetry.source]]
name = "internal"
url = "https://pypi.blindfolded.surgery"
priority = "explicit"

[tool.poetry.dependencies]
bs-config = { tag = "v1.0.1", extras = ["dotenv"], git = "https://github.com/BlindfoldedSurgery/bs-config.git" }
certifi = "2024.2.2"
click = "^8.1.3"
# dictated by python-telegram-bot
httpx = "*"
openai = "^1.0.0"
python = "~3.12"
python-telegram-bot = "20.8"
sentry-sdk = "^1.14.0"

[tool.poetry.group.dev.dependencies]
black = "^24.0.0"
mypy = "~1.9"
pytest = "^8.0.0"
ruff = "0.3.2"
types-requests = "^2.28.11"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true
warn_return_any = false

[[tool.mypy.overrides]]
module = "tests.*"
strict = false
check_untyped_defs = true
disallow_untyped_defs = false

[tool.ruff]
extend-select = [
    "I001",
]

[tool.ruff.isort]
known-first-party = ["az"]
