[tool.poetry]
name = "vodka-az"
description = "Vodka A-Z"
version = "1.0.0"
authors = ["OpenAlcoholics <team@openalcoholics.group>"]
license = "MIT"
packages = [
    { include = "az", from = "src" }
]

[tool.poetry.dependencies]
certifi = "2023.7.22"
click = "^8.1.3"
httpx = "^0.25.0"
openai = "^0.28.0"
python = "~3.11"
python-dotenv = "^1.0.0"
python-telegram-bot = "20.6"
sentry-sdk = "^1.14.0"

[tool.poetry.group.dev.dependencies]
black = "^23.0.0"
mypy = "^1.5.0"
pytest = "^7.4.0"
ruff = "0.0.292"
types-requests = "^2.28.11"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true
warn_return_any = false

[[tool.mypy.overrides]]
module = "tests.*"
strict = false
check_untyped_defs = true
disallow_untyped_defs = false

[tool.ruff]
extend-select = [
    "I001",
]

[tool.ruff.isort]
known-first-party = ["az"]
