[tool.poetry]
name = "az"
description = "Vodka A-Z"
version = "1.0.0"
authors = ["OpenAlcoholics <team@openalcoholics.group>"]
license = "MIT"

[tool.poetry.dependencies]
certifi = "2023.7.22"
click = "^8.1.3"
httpx = "^0.24.1"
openai = "^0.28.0"
python = "~3.11"
python-dotenv = "^1.0.0"
python-telegram-bot = "20.5"
sentry-sdk = "^1.14.0"

[tool.poetry.group.dev.dependencies]
black = "^23.0.0"
isort = "^5.12.0"
mypy = "^1.5.0"
pytest = "^7.4.0"
types-requests = "^2.28.11"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true
warn_return_any = false

[[tool.mypy.overrides]]
module = "tests.*"
strict = false
check_untyped_defs = true
disallow_untyped_defs = false
