---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secrets
spec:
  # 7 days
  refreshInterval: "168h"
  secretStoreRef:
    name: scaleway-prep-vodka-bot
    kind: ClusterSecretStore
  data:
    - secretKey: SENTRY_DSN
      remoteRef:
        key: "name:sentry-dsn"
        decodingStrategy: None
  dataFrom:
    - extract:
        key: "name:manual-secrets"
