apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secrets
stringData:
  OPENAI_TOKEN: "{{ .Values.openai.apiKey }}"
  SENTRY_DSN: "{{ .Values.sentry.dsn }}"
  TELEGRAM_TOKEN: "{{ .Values.telegram.apiKey }}"
