apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secrets
stringData:
  OPENAI_TOKEN: {{ .Values.openai.apiKey | quote }}
  SENTRY_DSN: {{ .Values.sentry.dsn | quote }}
  TELEGRAM_TOKEN: {{ .Values.telegram.apiKey | quote }}
